In [3]:
import pandas as pd
import numpy as np

In [4]:
# Load the both dataset
true_df = pd.read_csv("D:\Ai driven News credability and influence analysis\data\Fake.csv")
true_df.head(5)

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [5]:
fake_df = pd.read_csv("D:\Ai driven News credability and influence analysis\data\True.csv")
fake_df.head(5)

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [6]:
true_df["label"] = 1
fake_df["label"] = 0

In [7]:
true_df.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",1
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",1

In [8]:
# Combining Both the dataset  && shuffle dataset to avoid ordering bias
combined_df = pd.concat([true_df , fake_df] , ignore_index = True)

combined_df = combined_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [10]:
combined_df.to_csv("../data/combined_news.csv", index=False)

In [ ]:
# total rows & col
df.shape

(44898, 5)

In [ ]:
# col names + data types + missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    44898 non-null  object
 1   text     44898 non-null  object
 2   subject  44898 non-null  object
 3   date     44898 non-null  object
 4   label    44898 non-null  int64
dtypes: int64(1), object(4)
memory usage: 1.7+ MB

In [ ]:
# class Distribution
df["label"].value_counts()

label
1    23481
0    21417
Name: count, dtype: int64

In [ ]:
# Basic statistics
df.describe()

              label
count  44898.000000
mean       0.522985
std        0.499477
min        0.000000
25%        0.000000
50%        1.000000
75%        1.000000
max        1.000000

In [ ]:
# text length
df["text_length"] = df["text"].apply(lambda x: len(str(x).split()))

In [ ]:
df["text_length"].describe()

count    44898.000000
mean       405.282284
std        351.265595
min          0.000000
25%        203.000000
50%        362.000000
75%        513.000000
max       8135.000000
Name: text_length, dtype: float64

In [ ]:

df.groupby("label")["text_length"].mean()

label
0    385.640099
1    423.197905
Name: text_length, dtype: float64